# Generated by Django 3.1.4 on 2020-12-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_auto_20201220_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_active',
        ),
    ]
