# Generated by Django 3.1.4 on 2020-12-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_auto_20201223_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
