# Generated by Django 3.1.4 on 2021-01-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_auto_20201231_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Actual quantity'),
        ),
    ]
