# Generated by Django 3.1.5 on 2021-01-04 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_itemstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstats',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.item'),
        ),
    ]
