# Generated by Django 3.1.5 on 2021-01-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_auto_20210104_2231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemStats',
        ),
    ]
