# Generated by Django 3.1.5 on 2021-01-05 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_delete_itemstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
