version: '3.7'
services:

  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: on-failure

  redis:
    image: "redis:alpine"
    hostname: "redis"
    restart: on-failure

  web:
    build: .
    entrypoint: "/usr/src/app/entrypoint.sh"
    container_name: web
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    restart: on-failure

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A project worker --loglevel=info
    env_file:
      - ./.env.dev
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
    restart: on-failure
