version: '3.7'
services:

  db:
    image: postgres:12.0-alpine
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: on-failure

  redis:
    image: "redis:alpine"
    container_name: redis
    hostname: "redis"
    restart: on-failure

  app:
    build: ./trading_service
    container_name: app
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: on-failure

  celery:
    build: ./trading_service
    container_name: celery
    entrypoint: sh -c "sleep 10 && celery -A core worker -B --scheduler django -l INFO -f celery_log.txt"
    env_file:
      - ./.env.dev
    volumes:
      - .:/usr/src/app/
    depends_on:
      - app
    restart: on-failure

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./trading_service/staticfiles:/media/static/
    depends_on:
      - app