# Generated by Django 3.1.4 on 2020-12-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_remove_offer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
