# Generated by Django 3.1.4 on 2020-12-23 13:47

from django.db import migrations, models
import trading.models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_offer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.CharField(choices=[('SELL', 'Sell'), ('BUY', 'Buy')], default=trading.models.OrderType['SELL'], max_length=6),
        ),
    ]
